Shine1594
code-squad/javascript-food pull request #10
Opened 2017-12-20 06:38 UTC by shine1594

무한 슬라이딩 구현하였고 여러 번 연속으로 이벤트 발생 시에 발생하는 버그를 수정중입니다.

2017-12-21 05:48 UTC, crongro requested changes
전체적으로 잘 구현됐어요. 

몇개 리뷰는 참고하시길.

그리고 컴포넌트에서 외부함수를 받아서 처리할 수도 있을텐데요.
즉 컴포넌트안에 있지 않고 외부에 있는 것이 더 나을거 같은  함수가 있다면 1개만 정해서 컴포넌트 밖에서 선언하고 이를 컴포넌트에서 받아서 실행하도록 시도해보세요. 

컴포넌트의 응집성은 낮아지지만, 컴포넌트가 좀더 핵심적인 기능에 집중할수 있는 방법이에요.

2017-12-21 05:48 UTC, nigayo commented on js/carousel.js
> +  animations: {
animations 코드를 객체로 묶어서 두니, 애니메이션 방법의 변경이 생길때 좀더 쉽게 수정할 수 있어보여요.
그리고 이렇게 두고 보니, animation이 변경될수도 있고, 또 추가될 수도 있을거 같아요. 
지금 수정은 꽤 어려울 거 같긴한데요. 
아예 이 컴포넌트에서 분리해서 관리할 수 있는 방법도 가능은 할까요? 
(이건 수정이 아니고, 고민만 해보기)

2017-12-21 05:48 UTC, nigayo commented on js/carousel.js
> +          this.addClonedElements();
클론을 초기화때 한번하지 말고, 미리 만들어두는 건 어떨까유?

2017-12-21 05:48 UTC, nigayo commented on js/carousel.js
> +  Object.assign(this, {
괜찮은 방법이네요. 
참고로 브라우저 지원범위는 살펴보세요.

2017-12-21 05:48 UTC, nigayo commented on js/carousel.js
> +    this.itemContainer.children.forEach(item => {
여기 코드는 css class를 추가하기 어려운상황인가요?

2017-12-22 07:17 UTC, shine1594 commented on js/carousel.js
> +          this.addClonedElements();
infinity loop 설정에 따라 clone을 만들거나 안만들거나 선택해야되서 초기화 과정에서 처리해야될것 같습니다.

2017-12-26 02:02 UTC, merged