Implement Autocomplete
code-squad/javascript-food pull request #15
Opened 2018-01-12 02:37 UTC by sphilee

2018-01-12 05:51 UTC, crongro requested changes
기존 프레임웍 구조에 잘 섞이면서 기능추가가 쉬워보이는데 어때요?  

뷰파일분리 검토해보죠.

2018-01-12 05:51 UTC, nigayo commented on src/commonView.js
> +    enterAutoComplete() {
setTimeout을 왜 사용했어요?

2018-01-12 05:51 UTC, nigayo commented on src/commonView.js
> +    renderAutoComplete(term, suggestions) {
autocomplete 부분을 별도 view 파일로 분리하면 어때요?

2018-01-12 09:26 UTC, sphilee commented
@nigayo 캐시로 Ajax요청 다시 보내지 않기. 완료했습니다.

2018-01-15 03:00 UTC, crongro approved these changes
네이밍은 참고해서 수정해두세요.
아는 것 같긴한데, async를 쓸때 비동기로직에 대한 이해는 정확히 하고 넘어가세요.

2018-01-15 03:00 UTC, nigayo commented on src/autocompleteView.js
> +    render(viewCmd, ...parameter) {
프로그래밍에서 다른 용어를 직접쓰지 않는게 좋아요.
params 과 같은 다른 이름으로..

2018-01-15 03:00 UTC, nigayo commented on src/autocompleteView.js
> +            `<li class="autocomplete_suggestion" data-value="${suggestion[0]}">
여기 템플릿이 눈에 잘 안들어오는데, js에서 템플릿원본을 분리할 수 없을까요?  
지금 방식은 템플릿이 길면 더 문제가 될 듯.

2018-01-15 03:00 UTC, nigayo commented on src/controller.js
>          if (!key || (key < 35 || key > 40) && key !== 13 && key !== 27) {
keycode가 나열된 이 조건문이 길기도하고, 무슨의도인지 알기 어렵네요.
이걸 하나의 함수로 이름짓고 그 안에서 구현해두고 불러오면 어떨까요?
if(checkXXXKeycodes())  라던가...

2018-01-15 03:00 UTC, nigayo commented on src/controller.js
>              const [thresholdLeft, thresholdRight] = [-20 - (foodData.length * 2.5), -20 + (foodData.length * 2.5)];
여기 좀 줄여보세요.
foodData.length * 2.5 이코드는 반복적인 부분이라 변수로 담아두어도 될 거 같고.

2018-01-15 03:00 UTC, nigayo commented on src/controller.js
>          this.initBestBanchan(this.urlList.bestBanchan);
initSlide, initBestBanchan 메서드는 async함수들로 비동기 로직을 모두 담고 있는데요.
비동기 전체 로직의 순서는 보장되지 않아요.
다시말해 initBestBanchan안에 비동기 로직이 먼저 실행되고, initSlide안의 비동기 로직이 나중에 실행될 수도 있는거죠.
지금은 순서가 중요하지 않아서 문제가 되지 않아도, 그점을 인지하고는 있어야겠죠.

2018-01-15 03:01 UTC, merged