[Lumi] 리팩토링 / 슬라이딩리스트 추가
code-squad/javascript-food pull request #20
Opened 2018-04-03 03:29 UTC by LumiLoves

한 것
* 객체의 역할과 정의, 범용성 고려하여 코드 리팩토링 
  * 결과물1: 코드
  * 결과물2: README (바꾼 구조에 대해 설명도 할 수 있어야 한다고 하셔서 글로 정리. 리뷰할때 말씀하신 의도와 맞는지 확인 부탁드립니다.)
* 리스트슬라이더 기능 추가 (+ 기본기능, 무한슬라이딩, 추가슬라이딩구현)

남은 해결사항
* 리스트슬라이더의 슬라이딩그룹이 3개이하(1개, 2개)일때 처리
* 리스트슬라이더 역방향 애니메이션 버그 수정

2018-04-03 06:48 UTC, crongro requested changes
여러개의 모듈(클래스)로 잘 나누었네요.

클래스별로 일관된 방식으로 동작되고 있어서 좋습니다.

유사한 컴포넌트를 만들고 추가할때 편리할 거 같고요.

리뷰참고하면서, 현재 클래스들의 역할을 조금더 조정하면 좋겠습니다.

2018-04-03 06:48 UTC, crongro commented on README.MD
> +  * 렌더링은 옵션이라고 생각. 렌더링할때 안한때 다 유연하게 동작하도록 분리하는걸 고민 많이함.
여기서 렌더링은 어떤건가요?

2018-04-03 06:48 UTC, crongro commented on README.MD
> +  * ajax없이 단순 render시에는 util의 template을 사용.
ajax 없을때는 util이고, 
ajax 있을때는 클래스안에서 처리하고, 
글만 봐서는 약간 어색한 구석이 있네요.

2018-04-03 06:48 UTC, crongro commented on README.MD
> +  * List Slider와 Visual Slider의 공통적인 기능을 부모 클래스인 Slider로 분리하고 상속받게 함.
공통부분을 담당하는 Slider클래스를 만든 건 아주 좋습니다.

2018-04-03 06:48 UTC, crongro commented on src/js/bmc-page-main.js
> +const mainPage = (function(lumiUtil, Renderer, Tab, VisualSlider, ListSlider) {
mainPage에서 여러가지 컴포넌트를 초기화만 해주니까 좋네요.

2018-04-03 06:48 UTC, crongro commented on src/js/bmc-page-main.js
> +const mainPage = (function(lumiUtil, Renderer, Tab, VisualSlider, ListSlider) {
아래쪽에, map을 사용해서 listSlider한 것도 좋습니다. 추가될 때 그 쪽 코드 수정은 안해도 되겠네요.

2018-04-03 06:48 UTC, crongro commented on src/js/bmc-ui/ListSlider.js
> +  constructor({ wrapperElem, renderer, dom }) {
모든 컴포넌트들이 일관되게 동작하는 게 어려운일인데 그걸 잘 지켰네요.
전역에 있는 걸 바로 쓰지 않고, 이렇게 생성자에서 받도록 한 것도 좋은 아이디어네요.

2018-04-03 06:48 UTC, crongro commented on src/js/bmc-ui/Tab.js
> +    this.activeIndex = 0;
값을 초기화 시켜주는 코드 같으나, 함수 이름이 좀 거창하네요.

2018-04-03 06:48 UTC, crongro commented on src/js/bmc-ui/Tab.js
> +    this.contentItems = this.wrapperElem.querySelectorAll('.tab-content-group-box > li');
업데이트 해주기보다, 
이 값이 필요할때 selector하는게 좀더 정확할 거 같아요.

2018-04-03 06:48 UTC, crongro commented on src/js/bmc-ui/Tab.js
> +      currentObject.items[0].isGroupStart = true;
0, 2 대신에 의미있는 걸 넣을수도 있나요?

2018-04-03 06:48 UTC, crongro commented on src/js/bmc-ui/Tab.js
> +  _handleRenderData(renderData) {
handling하는 건 맞는데, 좀더 구체적인 이름을 지으면 좋겠어요.

2018-04-03 06:48 UTC, crongro commented on src/js/bmc-ui/ListSlider.js
> +    (needRendering)? this.render() : this.init();
rendering이 필요 없는게 아니고, renderer의 사용이 필요한지 아닌지죠? 
그러면 renderer을 늘 쓰고, ajax가 필요 없는 경우와 있는 경우에 따라서 renderer가 다르게 동작되는건 어때요?

2018-04-03 06:48 UTC, nigayo commented on src/js/bmc-ui/ListSlider.js
> +    this.activeElements(0, true);
혹시 Ajax이후 렌더링 되기전에 , 해도 되는 일이 있으면 하도록 하세요~

2018-04-03 06:48 UTC, nigayo commented on src/js/bmc-ui/ListSlider.js
> +class ListSlider extends Slider {
Slider를 공통으로 뺀건 아주 좋고요.

모든 Slider의 모든 부모인지, 아니면 두 개의 공통된 기능만 담은 부모인지, 
이런 정의를 해둘 필요는 있겠어요.
정의를 어떻게 하는가에따라서, 여기에 담을 기능을 정확히 결정할 수 있을 거 같네요.

2018-04-03 06:48 UTC, nigayo commented on src/js/bmc-ui/Slider.js
> +    this.contentItems.item(indexSet.prev).classList.remove('prev');
배열의 함수형 메서드들을 써볼 수 있을거 같아요. (시도~)
_addDirectionClass이함수에서도 마찬가지고요.

2018-04-03 06:48 UTC, nigayo commented on src/js/bmc-ui/Slider.js
> +    this.activeIndex = i || 0;
default parameters ~

2018-04-03 06:48 UTC, nigayo commented on src/js/bmc-ui/ListSlider.js
> +    const numberOfGroups = 4;
이런 값들은, 옵션으로 빼주고, 4가 아닌 경우도 동작가능하게 할 수 있나요?

2018-04-03 06:48 UTC, nigayo commented on src/js/bmc-ui/ListSlider.js
> +    if (target && target.nodeName === 'A' || target.nodeName === 'I') { this.activeElements(newIndex); }
지금도 별문제는 없지만, A, I 보다는 좀더 의미있는 selector문법을 사용할수 있다면 더 좋겠네요.
html에 data 속성을 쓸수도 있겠네요.

2018-04-03 06:48 UTC, nigayo commented on src/js/bmc-ui/VisualSlider.js
> +    const OPACITY_INTERVAL_VALUE = 0.11;
이런값도 옵션으로 받기.

2018-04-03 06:48 UTC, nigayo commented on src/js/bmc-ui/VisualSlider.js
> +  _injectContentsIndex() {
이녀석, _injectContentsIndex과
이녀석, _injectDotBtnsIndex이

비슷하네요 사실. 인자만 다른 듯.  
이름을 주어서 명시적으로 구분한건 좋지만... 그냥 합칠 수도 있을거 같네요
약간 개인취향이긴함.

2018-04-03 06:48 UTC, nigayo commented on src/js/bmc-ui/Renderer.js
> +class Renderer {
다른곳에서 말했지만, Renderer가 하는 일의 범위를 어떻게 할지 고민스럽네요.
Ajax가 필요할까? localstorage에서 데이터를 가져오면 어떡하지?  
데이터를 가져오는 걸하지말고, templating위주로 집중하는건 어떨까? 
등을 고민해보세요.

2018-04-26 08:42 UTC, LumiLoves commented
comment에 대한 사항 전체적으로 수정하였고,
핵심 수정 항목은 아래와 같습니다.

* 클라이언트 측 렌더링과정 개선
  * async, await 적용하여 동기적인 코드처럼 보이도록 개선, 콜백 삭제
  * 데이터를 가져오는 방법을 인스턴스 생성시 주입받아 사용할 수 있도록 개선
* XHR 대신 fetch 사용 및 pollyfill 추가 (~ IE8)
* listSlider에서 한번에 보이는 아이템 갯수를 옵션값으로 받아 유동적으로 렌더링 가능하게 함 (마크업, 기능 모두 유연하게 동작되도록)
* ES6의 디폴트 파라미터 적용
* 추상적인 메소드명, 클래스 내에서 의미를 부여하지 않고 넣은 value들은 좀 더 의미있는 변수명에 담아서 사용

2018-04-26 08:49 UTC, LumiLoves reviewed
comment에 대한 사항 전체적으로 수정하였고,
핵심 수정 항목은 아래와 같습니다.

* 클라이언트 측 렌더링과정 개선
  * async, await 적용하여 동기적인 코드처럼 보이도록 개선, 콜백 삭제
  * 데이터를 가져오는 방법을 인스턴스 생성시 주입받아 사용할 수 있도록 개선
* XHR 대신 fetch 사용 및 pollyfill 추가 (~ IE8)
* listSlider에서 한번에 보이는 아이템 갯수를 옵션값으로 받아 유동적으로 렌더링 가능하게 함 (마크업, 기능 모두 유연하게 동작되도록)
* ES6의 디폴트 파라미터 적용
* 추상적인 메소드명, 클래스 내에서 의미를 부여하지 않고 넣은 value들은 좀 더 의미있는 변수명에 담아서 사용

2018-04-26 08:49 UTC, LumiLoves commented on README.MD
> +  * ajax없이 단순 render시에는 util의 template을 사용.
이것도 rendering 과정을 전체적으로 수정해서 필요없는 문장이 되었고,
개선된 과정에 대한 설명을 더 추가하여 기재해봤습니다.

2018-04-26 08:49 UTC, LumiLoves commented on README.MD
> +  * 렌더링은 옵션이라고 생각. 렌더링할때 안한때 다 유연하게 동작하도록 분리하는걸 고민 많이함.
클라이언트 사이드 렌더링을 말한 것인데,
애매한 용어를 쓴 것 같아서 좀 더 정확하게 수정했습니다.

2018-04-26 08:49 UTC, LumiLoves commented on src/js/bmc-ui/Tab.js
> +    this.activeIndex = 0;
_createElementsData, _createUIData ==> _bindElemProps, _bindUIProps

* create보다 bind가 더 적절해보여 변경했고,
* data가 너무 추상적이고 여기저기 중복으로 쓰이는거 같아서 property라고 구체적으로 변경해봤습니다.

2018-04-26 08:49 UTC, LumiLoves commented on src/js/bmc-ui/Tab.js
> +    this.contentItems = this.wrapperElem.querySelectorAll('.tab-content-group-box > li');
_updateRenderElemData ==>  _bindPropsAfterRender

클라이언트 사이드에서 만들어준 UI에 의존하는 Property를 인스턴스 데이터로 바인딩하는 코드인데
의도가 명확히 안보이는 네이밍같아서 좀 더 구체적으로 바꿔봤습니다.

2018-04-26 08:49 UTC, LumiLoves commented on src/js/bmc-ui/Tab.js
> +      currentObject.items[0].isGroupStart = true;
의미있는 변수명에 담아서 사용하도록 변경해봤습니다.

2018-04-26 08:49 UTC, LumiLoves commented on src/js/bmc-ui/Tab.js
> +  _handleRenderData(renderData) {
_handleRenderData ==> _remodelRenderData

받아온 ajax data를 렌더링하기 유리한 구조로 바꿔주는 것이므로
remodel이 더 적합해보여 바꿨습니다~

2018-04-26 08:49 UTC, LumiLoves commented on src/js/bmc-ui/ListSlider.js
> +    (needRendering)? this.render() : this.init();
저걸 개발할 때는 너무 코드를 만드는 입장에서 생각하고 개발한 거 같아요.

좀 더 실제 과정에 비유하여 자연스럽게 생각해보니,
renderer가 선언된 여부에 따라 처리하는게 아니고

돔이 있는지 없는지를 체크해서 
=> 없으면 클라이언트 측 렌더링 과정을 거친 후 init을 하고
=> 있으면 (렌더링과정 필요없이) init만 하면 되겠더라구요.

그리고 관련된 과정은 async, await를 한번 사용해봤습니다. (콜백이 없어지고 가독성이 높아졌어요!)

2018-04-26 08:49 UTC, LumiLoves commented on src/js/bmc-ui/ListSlider.js
> +    this.activeElements(0, true);
Ajax이후 렌더링 되기전에 필요한 일에 해당되는 경우가 
data를 view에 맞도록 조작해줄 수 있는 것 같고,
_remodelRenderData 메서드에 해당하는 거 같습니다~

2018-04-26 08:49 UTC, LumiLoves commented on src/js/bmc-ui/ListSlider.js
> +class ListSlider extends Slider {
모든 슬라이드 공통으로 쓸 수 있을 것 같은 기능만 빼놓았다고 생각하는데,
예상대로 될지는 정확히 가늠을 못하겠네요~

일단 모든 슬라이드의 부모라고 정의하고 주석에 표현하도록 했습니다.

2018-04-26 08:49 UTC, LumiLoves commented on src/js/bmc-ui/Slider.js
> +    this.contentItems.item(indexSet.prev).classList.remove('prev');
배열 메서드로 적용해 보았습니다

2018-04-26 08:49 UTC, LumiLoves commented on src/js/bmc-ui/Slider.js
> +    this.activeIndex = i || 0;
디폴트 매개변수를 es6에서 제공하는 문법형식으로 전체적으로 바꿔봤습니다.

2018-04-26 08:49 UTC, LumiLoves commented on src/js/bmc-ui/ListSlider.js
> +    const numberOfGroups = 4;
그룹별 아이템갯수를 옵션으로 받아서 유동적으로 렌더링 가능하게 변경해보았습니다. (마크업과 기능 모두)
=> 호출하는 리스트슬라이딩 인스턴스가 3개 있어서 2,3,4개씩 각기 다른 옵션을 주어 테스트 해봤습니다.

2018-04-26 08:49 UTC, LumiLoves commented on src/js/bmc-ui/ListSlider.js
> +    if (target && target.nodeName === 'A' || target.nodeName === 'I') { this.activeElements(newIndex); }
[질문] 이것은 마크업 구조상 좋은 아이디어가 떠오르지 않아 구두로 질문드리겠습니다.

2018-04-26 08:49 UTC, LumiLoves commented on src/js/bmc-ui/VisualSlider.js
> +    const OPACITY_INTERVAL_VALUE = 0.11;
구현했습니다~

2018-04-26 08:49 UTC, LumiLoves commented on src/js/bmc-ui/VisualSlider.js
> +  _injectContentsIndex() {
전체적으로 다시 보니 클래스 안에서 한번 밖에 호출하지 않고,
그냥 단순히 dom util을 한줄 호출하는 코드 뿐이라 클래스에서 별도로 메서드로 뺄 필요가 없어보여 삭제했습니다 ~~

2018-04-26 08:49 UTC, LumiLoves commented on src/js/bmc-ui/Renderer.js
> +class Renderer {
데이터를 가져오는 방법이 다양할 수 있으므로
생성시 매개변수로 주입하여 사용할 수 있게 변경해 보았습니다.
예) ajax, localStorage, cache 등등..

2018-04-27 04:42 UTC, crongro approved these changes
이거 일단 머지할게요. 
다음 미션을 하게 되면, 
구두로 말한대로 Renderer를 개선하는 걸 시도해보시고.
그 구조에서 자동완성 UI를 만들어보세요.

2018-04-27 04:42 UTC, merged