Step2/menu layer
code-squad/javascript-food pull request #26
Opened 2018-07-17 15:02 UTC by amorfati0310

메뉴 레이어가 마우스 hover됬을 떄 나오도록 구현 하였습니다

2018-07-18 02:26 UTC, crongro requested changes
본격개발이 시작됐군요.
리뷰 몇 개 남겨봅니다.

2018-07-18 02:26 UTC, crongro commented on .babelrc
> +  "presets": ["es2015"]
뜻은 알죠? 
트랜스파일링된 결과코드를 한번 보세요.
어떻게 코드가 변경됐는지 비교하면서 es6-es5의 차이를 한번확인해보세요.

2018-07-18 02:26 UTC, crongro commented on js/components/Shared/Dropdown.js
>      this.showState = !this.showState;
지금처럼 flag 를 두는 것도 나쁘진 않아요.
하지만 때론 그런 상태값을 별도로 두지 않는다면 더 좋아요. style.display값을 추출해서 판단하는 식으로 하는건 어떨까요?

2018-07-18 02:26 UTC, crongro commented on js/components/Shared/Dropdown.js
> +    if(triggerSelector){
triggerSelector가 옵션인가보죠?  조건문이 있길래. 필수라면 조건문은 없애도 될 듯.

2018-07-18 02:26 UTC, crongro commented on js/components/Shared/Dropdown.js
> +  constructor(selector, triggerSelector) {
selector도 triggerSelector처럼 좀더 이름으로 의도를 나타내면 좋겠네요.

2018-07-18 02:26 UTC, crongro commented on js/components/Shared/Dropdown.js
>      this.dropdwonEl.innerHTML = template(data);
template 메서드는 어디서 갑자기 나타난거죠? import 를 통해서 명시적으로 선언해서 쓰던가 해야할 듯.

2018-07-18 02:26 UTC, crongro commented on js/app.js
>    appDownLoadEl.render(dropdownTemplate, appDownLoad);
render를 외부에서 부르고 있는데요.
구체적인 컴포넌트의 행위를 밖에서 표현하는 거 같아요. render를 하는지를 밖에서 알필요 없이, 외부에서는 '초기화'한다! 라고만 판단하게 하면어때요?

appDownLoadEl.init() 이나 initialize라던가 같은 메서드를 만들어서 부르는 거죠.
그리고 컴포넌트안의 init 메서드 안에서는 render를 할 수도 있고, 안할수도 있고, 또 다른 가능을 추가로 할 수도 있고요.

이처럼 바깥쪽에서는 추상화된 메서드를 호출하는 것이 좀더 느슨한 관계를 만들 거 같아요.

2018-07-18 08:35 UTC, amorfati0310 commented
크으 감사합니다 피드백 수정해서 반영하겠습니다 ~~ :D

2018-07-18 08:36 UTC, amorfati0310 commented on js/components/Shared/Dropdown.js
>      this.dropdwonEl.innerHTML = template(data);
크롱 이부분 이해가 잘 안됩니다. template을 받아서 쓰도록  한 부분인데 지금은  import를 app.js에서 template을 받아서 처리하고 있는데 어떤 방식을 얘기하신 부분인지 잘 모르겠습니다 ㅜ

2018-07-18 08:37 UTC, nigayo commented on js/components/Shared/Dropdown.js
>      this.dropdwonEl.innerHTML = template(data);
아 네 이부분 사실 아래 부분과 관련된 부분인데요.
여기 리뷰는 무시해주세요 ^^;
(template을 인자로 받고 있는걸 못봤음)

2018-07-19 23:53 UTC, crongro approved these changes
네 es5변환한코드보면 defineProperty라는게 있죠. 객체의 속성을 구체적으로 정의할 수 있는 것인데, 많은 속성들이 있어요. 많이 쓰이진 않지만 어떤 것들이 있는지 훑어볼 필요는 있습니다.

render를 안으로 옮겼군요. 내부의 구체적인 일이 있다면 감출 수 있다면 감추는게 좀더 나아요. (대체로그렇죠). 추상화라는 것이 그런 점입니다.

2018-07-19 23:53 UTC, merged

2018-07-20 03:03 UTC, amorfati0310 commented
리뷰 감사합니다 defineProperty와 추상화 가지고 다음 과정 진행하겠습니다 ~~ 👍