Shine1594
code-squad/javascript-food pull request #4
Opened 2017-11-28 05:39 UTC by shine1594

'TAB UI' lesson 완료하였습니다 :)

2017-11-28 07:06 UTC, crongro requested changes
커다란 
makeTabs 함수를 얼릉 나눠야 할 듯.

function prototype으로 바꿔서 리팩토링 지금 해보면 어때요?

2017-11-28 07:06 UTC, nigayo commented on js/main.js
> +function requestData(params) {
이함수는 
재사용이 빈번한 함수일 수 있어, 유틸리티 객체로 묶어두는 게 어때요?

2017-11-28 12:22 UTC, shine1594 commented
생성자 호출 패턴으로 모듈화 진행하였습니다. 리뷰 부탁드릴게요:)

2017-11-30 01:42 UTC, crongro requested changes
자 조금 보완하고 갑시다.

2017-11-30 01:42 UTC, crongro commented on js/main.js
> +function requestData(params) {
이런 것들을 묶어서 유틸리티 메서드를 만들어서 관리해보세요.  
프로젝트 할때마다 재사용~!

2017-11-30 01:42 UTC, crongro commented on js/tab_menu.js
> +  constructor: TabMenu,
constructor 를 선언한 이유를 코멘트로 남겨주세요.

2017-11-30 01:42 UTC, crongro commented on js/tab_menu.js
> +      const $button = document.createElement('li');
$라고 이름을 쓴 이유는?

2017-11-30 01:42 UTC, nigayo commented on js/tab_menu.js
> +      const $button = document.createElement('li');
DOM을 초기에 js로 만드는 이유가 궁금하네요.

2017-11-30 01:42 UTC, nigayo commented on js/tab_menu.js
> +    this.thumbnailLists.forEach((thumb) => thumb.style = 'display: none;');
이렇게 css 스타일을 초기에 JS에서 해야할까요?

2017-11-30 01:42 UTC, nigayo commented on js/tab_menu.js
> +    const tags = tempNode.querySelector('.thumbnail__tags');
변수 선언은 가급적 함수 위쪽으로 올려서 몰아서 선언해요.

2017-11-30 01:42 UTC, nigayo commented on js/tab_menu.js
> +  getThumbnailHTML: function(template, data) {
이 함수가 하는일이 좀더 html을 반환하는 것에만 집중하게 할 수 있으면 좋겠음

2017-11-30 01:42 UTC, nigayo commented on js/tab_menu.js
> +    this.buttonsContainer.addEventListener('click', (evt) => {
destructuring을 쓰면, target 을 받아도 되겠네요.

2017-11-30 01:42 UTC, nigayo commented on js/tab_menu.js
> +      this.buttonsContainer.children[currentIndex].classList.remove('active');
DOM구조가 변경될 수 있다는 점도 고려하면 좋아요.
class 나 data 속성을 사용해서 노드를 찾아가면 dom구조의 영향을 덜 타게 되겠죠.

2017-12-01 01:53 UTC, crongro requested changes
잘 구현했어요. 
리뷰보고 조금 수정해보죠.

2017-12-01 01:53 UTC, nigayo commented on index.html
> +        <li data-index="0" class="active"></li>
물론 기획에 따라서 active해야 할 대상이 달리질 수도 있긴하겠죠. 그렇다면야 HTML안에 고정해둘수는 없지만, 
기본active클래스를 이렇게 지정해두는 것이 좋아요.

2017-12-01 01:53 UTC, nigayo commented on js/tab_menu.js
> +      this.contentElements[currentIndex].style = 'display: none;';
자주 쓸 거 같은데 
none, block 해주는 간단한 유틸리티 함수를 만들어두는 게 좋겠어요.

2017-12-01 01:53 UTC, nigayo commented on js/carousel.js
> +  this.buttonPrev = this.container.querySelector('.carousel__btn--prev');
생성자안에 선언된 변수들 중에 여러메서드에서 사용하는 속성값이 아니면, 해당 메서드안에서 지역변수로 선언해서 쓰는게 좋겠어요.
 this.buttonPrev  가 사용되는 곳은 딱 한군데 메서드뿐이니, 그 메서드의 지역변수로 옮겨보죠.
다른 것도 이런것들이 있다면 마찬가지 옮기고요.

2017-12-01 01:53 UTC, nigayo commented on js/carousel.js
> +      const newItem = document.createElement('li');
이제 모든 코드를 createElement를쓰지않고, 
대체로 더 빠르다고 알려진 insertAdjacentHtml이나 innerHTML을 사용해서 DOM을 조작해볼까요?
이 메서드들이 더 빠르기도 하고, DOM 조작이 더 쉽습니다.

2017-12-01 01:53 UTC, nigayo commented on js/carousel.js
> +    this.pagination.children[nextIndex].classList.add('pagination__dot--active');
엘리먼트가 자주 사용되면 캐시해두세요.

var ch = document.body.querySelector("div").children;
ch.classList.remove('내클래스명이정말길지만의미있는거다");

2017-12-01 01:53 UTC, nigayo commented on js/carousel.js
> +    this.renderItems();
초기에 렌더링 되는 걸 역시 최소화 할 수 없을지 고민해보세요.

2017-12-01 01:53 UTC, nigayo commented on js/carousel.js
> +    for (let i = 0; i < this.images.length; i++) {
foreach를 쓰는식으로 일관성있게 바꾸는게 좋겠네요.

2017-12-01 05:47 UTC, shine1594 commented
피드백 주신거 반영해서 수정했습니다:)

2017-12-01 07:51 UTC, crongro requested changes
간결하고, 잘 구현됐어요.

질문에 답변 좀 해주시고, 필요한코드는 좀더 보완해보죠.

2017-12-01 07:51 UTC, nigayo commented on js/carousel.js
> +  this.classNames = {
이렇게 묶어둔 이유는 뭐에요?

2017-12-01 07:51 UTC, nigayo commented on js/carousel.js
> +    return (type === 'background')
똑똑하게 동작하게 되서 좋긴한데요. 꼭 필요한 코드인가요?

2017-12-01 07:51 UTC, nigayo commented on js/carousel.js
> +function Carousel({ images, selector, imageType, dotStyle, effect }) {
option을 객체로 받는건 좋네요.

2017-12-01 07:51 UTC, nigayo commented on js/carousel.js
> +function Carousel({ images, selector, imageType, dotStyle, effect }) {
selector가 아니고, 기준엘리먼트? 이라면 좀더 그럴싸한 이름을 지어줄 수 있어보여요.

2017-12-01 07:51 UTC, nigayo commented on js/carousel.js
> +    items[currentIndex].classList.remove(this.options.effect);
아래 4줄은 두줄씩 중복느낌인데, 없앨 수 있을까요?

2017-12-11 05:54 UTC, shine1594 commented
carousel 기능 구현 완료하였습니다 리뷰 부탁드릴게요:)

2017-12-11 07:42 UTC, crongro approved these changes
잘하셨어요.

리뷰참고하시고, 

기능버그(opacity 점점 줄게 하느거)와 
무한슬라이딩 되도록 만들어보죠.

일단 머지합니다.

2017-12-11 07:42 UTC, nigayo commented on js/carousel.js
> +  this.visibleItems = visibleItems || 1;
default parameter 라는 게 생겼는데. 그걸 적용해볼래요?

2017-12-11 07:42 UTC, nigayo commented on js/carousel.js
> +  this.speed = speed || '500ms';
속성 이름을 좀더 구체적으로 써볼래요? 
괜찮은 것도 있지만, speed,  effect등은  좀더 구체적이어야 할 듯.

2017-12-11 07:42 UTC, nigayo commented on js/carousel.js
> +  this.container = document.querySelector(selector);
selector 는 변경될 수 있어서, 차라리 document.querySelector(selector);를 대신 받는게 좀더 나을 거 같아요.

2017-12-11 07:42 UTC, nigayo commented on js/carousel.js
> +    Array.prototype.forEach.call(this.itemContainer.children, (item) => {
nodeList에 forEach가 있는지 찾아보고, 있으면 polyfill.js에 추가해서 사용하면 좋겠어요.
서비스 개발하면서 polyfill은 계속 쌓아두고요.

2017-12-11 07:42 UTC, nigayo commented on js/carousel.js
> +    return TabMenu.prototype.getThumbnailHTML(this.itemTemplate, item);
TabMenu의 메서드가 유틸리티처럼 필요했던 것이면, 그 메서드를 유틸리티로 옮겨두고 tab과Carousel에서 같이 쓰고요,

그것이 아니고, Carousel에서 tabmenu 클래스에 의존성이 있어서 접근해야 하는것이면, 이렇게 직접 메서드를 접근하지 말고, 인스턴스를 통해서 접근하는게 더 명시적인 방법같아요.

2017-12-11 07:42 UTC, nigayo commented on js/carousel.js
> +    buttonPrev.addEventListener('click', (evt) => {
지금도 좋지만, event delegation으로도 가능하겠죠?

2017-12-11 07:42 UTC, nigayo commented on js/carousel.js
> +  effects: {
객체를 잘 쓰니 좋군요.
좋은 방법이네요~

2017-12-11 07:42 UTC, merged