Step9/auto search
code-squad/javascript-food pull request #40
Opened 2018-08-17 09:04 UTC by amorfati0310

자동완성 기능 추가하였습니다 리뷰 부탁드리겠습니다 ~:D 

기획서에서는 Enter를 눌러야 input value가 바뀌는데 HighLight될 때 바로 바뀌는 편이 더 낫다고 생각해서 그렇게 작업을 하였습니다 Enter를 누르면 키워드 창이 닫히게 구현했습니다

2018-08-21 06:18 UTC, crongro requested changes
간만에 수정요청 드려요.
잘 구현했어요. 데모봐야겠다~

2018-08-21 06:18 UTC, crongro commented on js/Model/SearchFormModel.js
> +    return JSON.parse(localStorage.getItem(this.key)) || []
localstorage와 세션스토리지 차이를 알아두세요.

2018-08-21 06:18 UTC, crongro commented on js/Model/SearchFormModel.js
> +export default class SearchFormModel {
기능별로 m,v,c 코드가 있는것도 좋네요.
디렉토리 구성을 model 에 model을 몰아두는 것도 별 문제가 아니고 나쁘지 않은데요.
서비스단위로 mvc를 같이 묶어두는 것도 좋을 거 같아요.

2018-08-21 06:18 UTC, crongro commented on js/Model/SearchFormModel.js
> +    const hasSameData = keywordList.some(keywordData=>keywordData.keyword===data)
some 도 쓰는군요. 이녀석은 반복을 돌다가 필요할때 멈추기도 해서 좋은거 같아요.

2018-08-21 06:18 UTC, crongro commented on js/Model/SearchFormModel.js
> +    keywordList = [...keywordList, {id: keyWordCounts, keyword: data}]
object spread operator 도 있던데, 참고로 같이 알아두면 좋겠네요.

2018-08-21 06:18 UTC, crongro commented on js/Model/SearchFormModel.js
> +    const recentShowItems = 5;
5가 박혀 있는건 아쉽네요. 어제 공유한 링크에도 나왔지만 magic number없애기..

2018-08-21 06:18 UTC, crongro commented on js/app.js
>  import AjaxHelper from "./helper/AjaxHelper.js";
다시 AjaxHelper를 보면 과연 이녀석이 class형태여야만 하는가? 
그냥 AjaxHelper.js 안에는 여러가지 함수가 있고, 그중에 public한 것만 export해서 사용해도 되겠구나. 생각이들어요.
모든게 클래스일 필요는 없을 거 같아요.

2018-08-21 06:18 UTC, crongro commented on js/app.js
>  const main_slideListUrl = `${woowaDomain}/main`;
비슷한 url들을 namespace로 묶으면 좋겠네요.
const urls = {} 뭐 대충 이렇게.

2018-08-21 06:18 UTC, crongro commented on js/components/Shared/ScrollButton/ScrollButton.js
> +  handleUpDown(id){
별거 아니지만 id라는 매개변수 이름을 좀더 구체적으로 해야 무엇인지 알 거 같아요. 그냥 direction같기도 하고..

2018-08-21 06:18 UTC, crongro commented on js/components/Shared/SearchForm/SearchForm.js
> +  deBounceKeyEvents(e){
debounce구현했군요.

2018-08-21 06:18 UTC, crongro commented on js/components/Shared/SearchForm/SearchForm.js
> +    this.timer = setTimeout((e = event)=>this.setAjax(e), 200);
200이런숫자를 코드에 하드코딩 안하기.

2018-08-21 06:18 UTC, crongro commented on js/components/Shared/SearchForm/SearchForm.js
> +    this.keyWordList.innerHTML = keyWordListTemplate(keyword, keywordList)
외부모듈을 네임스페이스로 처리하도록 하는 건 어때요? 
Template.keywordList(keyword, keywordList) 이런식으로 처리하는 것도 좋을 듯.
이건 개취.

2018-08-21 06:18 UTC, crongro commented on js/components/Shared/SearchForm/SearchForm.js
> +    const willActiveEl = qs(`[data-id="${this.active_KeyWordIdx}"]`, this.keyWordList)
이름이 난해하네요 ㅎ

2018-08-21 06:18 UTC, crongro commented on js/components/Shared/SearchForm/SearchForm.js
> +  set_Active_KeyWordIdx(idx){
왜 이름에 갑자기 _ 를 추가했어요..?

2018-08-21 06:18 UTC, crongro commented on js/components/Shared/SearchForm/SearchForm.js
> +    this.handleChoseActiveIdx(type)
이렇게 넘겨주면 어때요? 
this.handleChoseActiveIdx({type:1})

2018-08-21 06:18 UTC, crongro commented on js/components/Shared/SearchForm/SearchForm.js
> +  bindGetRecentKeyWords(handler){
매개변수로 받은 handler 는 함수지만 무엇인지 좀더 이름에 표현을 할 수 있다면 더 좋을 듯.

2018-08-21 06:18 UTC, crongro commented on js/components/Shared/SearchForm/SearchForm.js
> +    this.init();
init이 모든 클래스에 있는거죠? 
그런 규칙이 있는거 아니면 this.bindEvents()를 여기서 바로 호출해도 될 듯.

2018-08-21 06:18 UTC, crongro commented on js/app.js
> +  const course_listSlider = new ListSlider('#list-slide-course', course_lsAjaxHelper, course_slideListUrl);
이정도는 괜찮은데, 함수와 클래스에서 파라미터 갯수가 많으면, 
 객체형태로 넘겨주고 destructuring으로 받는게 좀더 어떤 것들인지 알 수 있어서 좋아요.

2018-08-21 06:46 UTC, amorfati0310 commented on js/components/Shared/SearchForm/SearchForm.js
> +  set_Active_KeyWordIdx(idx){
3음절이 넘어가니 가독성이 .. 떨어지더라고요 ㅜㅜ 그래서 3음절 넘어가면 _underbar를 붙이는 것이 좋지 않을까 해서 붙여봤습니다

2018-08-21 06:46 UTC, amorfati0310 commented
리뷰  감사합니다 반영해서 수정하겠습니다 ~~

2018-08-21 07:02 UTC, amorfati0310 commented on js/Model/SearchFormModel.js
> +    return JSON.parse(localStorage.getItem(this.key)) || []
로컬스토리지, 세션 스토리지 모두 html5부터 추가된 브라우저에 보관소 
window.sessionStorage / window.localStorage
두개의 차이점은 로컬스토리지는 사용자가 clear하지 않는한 보관 됩니다. 
세션 스토리지는 탭을 끄면 사라집니다
모두  key: value(domString방식으로) 형태로 저장을 하고 꺼내올 때는 key값을 통해서 꺼내옵니다 
object로 조작하고 싶을 떄  JSON과 마찬가지로 JSON.stringify JSON.parse를 통해서 조작합니다

2018-08-21 07:02 UTC, amorfati0310 commented on js/Model/SearchFormModel.js
> +export default class SearchFormModel {
이렇게 한 번 사용해보고 장 단점 파악해보겠습니다 ~~:D

2018-08-21 11:17 UTC, amorfati0310 commented on js/components/Shared/SearchForm/SearchForm.js
> +    this.handleChoseActiveIdx(type)
type에 따라서 증가시킬지 감소시킬지 결정해서 지금 같은 방식을 택했는데 
크롱이 리뷰해주신 부분은  const change = type === UP ? -1: -1 을 해서 보내고 증감을 바로 하는 편이 더 좋을 것 같다고 리뷰해주신 건가요???

2018-08-22 00:43 UTC, crongro approved these changes
수고하셨어요!

2018-08-22 00:43 UTC, nigayo commented on js/components/Shared/SearchForm/SearchForm.js
> +const ZERO = 0;
상수값들도 비슷한 녀석들은 namespace로 묶는게 더 좋아요. 너무 많은 변수들이 생겨벼리면 헷갈림.

2018-08-22 00:43 UTC, merged