[HYEON] STEP 2 Refactoring : Prototype Pattern 적용
code-squad/javascript-food pull request #55
Opened 2018-10-22 06:54 UTC by antaehyeon

Prototype Pattern 과 Module Pattern 을 적용하여 JavaScript 로 hover 기능을 구현하였습니다.

2018-10-23 01:02 UTC, crongro requested changes
조금 수정하고 가죠.
모듈패턴과 prototype 을 잘 이해했으니, 다음미션부터는 
es modules & es6 class 조합으로 gogo.

2018-10-23 01:02 UTC, crongro commented on Model/Model.js
> +    const model = function() {
모듈패턴은 private 과 public을 구별하는 전통적인 방법이라는 점을 기억해두세요.

2018-10-23 01:02 UTC, crongro commented on Model/Model.js
> +    return new model();
빈...모델이라 현재는 형태만 있군요;;

2018-10-23 01:02 UTC, crongro commented on View/MainView.js
> +const vm = new MainViewModel(Model);
view의 역할은 무엇인가요? 
역할이 너무 없는 거 아닐까요?

2018-10-23 01:02 UTC, crongro commented on ViewModel/MainViewModel.js
> +        this.updateElementTextColor = function(element, colorData) {
this.updateElementDisplayProperty,
this.updateElementDisplayProperty,
this.updateElementBackgroundColor
이 메서드들은 다 비슷한 기능을 하네요. 하나로 통합해도 될 거 같고, 그렇게 돼도 부르는 쪽에서도 나쁘지 않아보일 거 같은데요.

이런식으로.
setCSS(viewElement, "color", "#333");

2018-10-23 01:02 UTC, crongro commented on main.js
> +    hover: function() {
prototype을 재정의하면 constructor 라는 속성이 없어져서, 별도로 추가해야합니다.

2018-10-23 01:02 UTC, crongro commented on main.js
> +    menu.hover();
이부분 코드를 읽어보면, 
menu 를 hove하는건가? 라는 느낌으로 보여져요.

2018-10-23 01:02 UTC, crongro commented on main.js
> +    childNodes.forEach((elem) => {
foreach 대신,
filter & map 은 어떨지.

2018-10-23 01:02 UTC, nigayo commented on main.js
> +function MenuListItem(element) {
이건 안쓰는 코드로 이해.

2018-10-23 09:45 UTC, crongro requested changes
main-test.js 를 리뷰했는데요..
맞나요? ㅎ

일단 코멘트 남깁니다. 
좀더수정해보세요~

2018-10-23 09:45 UTC, nigayo commented on js/test-ajax.js
> +function ajax(data) {
data 뿐만 아니라 , url , 로드이후에 처리할 콜백함수도 인자로 받으면 더 범용성있는 ajax함수가 되죠.

2018-10-23 09:45 UTC, nigayo commented on main-test.js
> +        this.currentElement.target = object.target;
currentElement는 자주쓰는 객체임으로, 이름을 좀더 짧게 써도 될 듯.

2018-10-23 09:45 UTC, nigayo commented on main-test.js
> +    this.getCurrentElement = function() {
함수는 모두 다 prototype안으로 옮기는게 좋아요. 여기 있을 이유가 없음.

2018-10-23 09:45 UTC, nigayo commented on main-test.js
> +function updateElementBackgroundColor(element, colorData) {
updateElementBackgroundColor 와 
updateElementBorder 도 
하나로 setCSS 로 합칠수도 있겠죠?

2018-10-23 09:45 UTC, nigayo commented on main-test.js
> +function updateElementTextColor(element, colorData) {
여기까지 4개의 함수가 별도 전역변수처럼 존재하고 있는데요. 
유틸리티면 ajax있는 것처럼 분리해서 관리하는게 좋고, 
아니고 MenuLayoutManager에 관련된 기능이면,  prototype안으로 옮기는게 맞을 거 같아요.

2018-10-26 03:16 UTC, nigayo commented
소스파일 중 리뷰의 대상이 무엇인지 좀 댓글로 남겨줄래요? 
비슷한 코드가 여러개 있는 거 같아서 헷갈림. @antaehyeon

2018-10-26 05:16 UTC, antaehyeon commented
아, 모르고 또 push 했군요. 코드정리 및 ES6 Class 문법 적용 후 push 하고 슬랙으로 연락드리겠습니다.

2018-10-30 00:00 UTC, crongro requested changes
시간은 없지만, 그래도 약간 개선하고 넘어가야 할 듯!
리뷰는 참고하고, 다 수정할 필요는 없고, 수정할 수 있는 부분만 수정하고 다시 push하세요~

2018-10-30 00:00 UTC, nigayo commented on app.js
> +    menuManager.hover();
hover 라는 이름이 좀더 구체적이면 좋겠네요.

2018-10-30 00:00 UTC, nigayo commented on js/BestDishesView.js
> +        oReq.open("GET", "http://crong.codesquad.kr:8080/woowa/best");
url을 인자로 받고 여기다가 하드코딩?

2018-10-30 00:00 UTC, nigayo commented on js/BestDishesView.js
> +            evt.target.style.backgroundColor = '#5FC8C6';
target이 자주 쓰이니까, destructuring으로 받아야겠군요.

2018-10-30 00:00 UTC, nigayo commented on js/BestDishesView.js
> +                foodDatas.push({
forEach말고,  적당한 higher order function을 써보세요.

2018-10-30 00:00 UTC, nigayo commented on js/BestDishesView.js
> +            return data;
brace 없는 조건문이면 한줄로 표현하기.

2018-10-30 00:00 UTC, nigayo commented on js/BestDishesView.js
> +            if (parentElement && i%3 === 0 || i === obj.length-1) {
3은 매직넘버.

2018-10-30 00:00 UTC, nigayo commented on js/BestDishesView.js
> +    createBestDishContainer(obj) {
좀 많은 일을 하는 편이라, createBestDishContainer 함수 아래에, 하위함수 더 만들어도 될 듯합니다.

2018-10-30 00:00 UTC, nigayo commented on js/BestDishesView.js
> +        button.style.backgroundColor = '#5FC8C6';
inline으로 스타일을 적용하는 것보다, css class 를 추가/삭제하는게 더 좋은거 알죠?

2018-10-30 00:00 UTC, nigayo commented on js/BestDishesView.js
> +        if (!opt) opt = "";
default parameter 를 사용해야겠군요.

2018-10-30 00:00 UTC, nigayo commented on js/BestDishesView.js
> +        bestSideDishesElements.forEach(element => {
이렇게 해도 되고, block 인 요소를 querySelector로 찾고, 그 엘리먼트만 none으로 해도 될 듯.

2018-10-30 00:00 UTC, nigayo commented on js/MenuManager.js
> +        element.addEventListener('mouseover', (evt) => {
({target}) => {

2018-10-30 00:00 UTC, nigayo commented on js/MenuManager.js
> +        element.addEventListener('mouseleave', () => {
mouseout 과 mouseleave 는 어떻게 다를까요?

2018-10-30 00:00 UTC, nigayo commented on js/MenuManager.js
> +        util.setCSS(element, 'backgroundColor', 'WHITE');
여기서는 setCSS를 잘 썼네요?

2018-10-30 00:00 UTC, nigayo commented on js/MenuManager.js
> +class MenuManager {
이름만 봐서는 모든 menu의  manager인가? 로 생각 될 거 같아요.
범용컴포넌트인가? 로 생각할 수 있죠.

2018-10-30 02:35 UTC, antaehyeon commented on js/MenuManager.js
> +        util.setCSS(element, 'backgroundColor', 'WHITE');
피드백을 적용하여 사용하였습니다 👍

2018-10-30 02:37 UTC, antaehyeon commented on js/MenuManager.js
> +        element.addEventListener('mouseleave', () => {
over 와 out 은 자식 엘리먼트 까지 동작하며, enter 와 leave 는 자식 엘리먼트까지 동작하지 않습니다.

2018-10-30 02:37 UTC, antaehyeon commented on js/BestDishesView.js
> +                foodDatas.push({
아.. 너무 어렵네요 -ㅠ-
추후 코드에 꼭 적용하도록 하겠습니다.. map, filter, reduce ....

2018-10-30 12:22 UTC, crongro approved these changes
수고했네요.
리뷰조금더 남겨요~
다음단계 만들어보죠.

2018-10-30 12:22 UTC, nigayo commented on app.js
> +    bestDishesView.request("http://crong.codesquad.kr:8080/woowa/best");
Ajax통신을 이해했다면 이제,
fetch API를 공부하고(XHR 통신과 같이 동작하지만 다름) 
다양한 기능을 지원하는 axios 라이브러리도 공부하세요.

2018-10-30 12:22 UTC, nigayo commented on css/main.css
> +	background-color: #5FC8C6 !important;
important 는 안쓰는 방법이 좋아요. 보다 근본적인 원인을 해결하셔야할듯.

2018-10-30 12:22 UTC, nigayo commented on js/BestDishesView.js
> +                foodDatas.push({
이정도는 기본입니다. 공부하세요 ㅎ

2018-10-30 12:22 UTC, nigayo commented on js/BestDishesView.js
> +            if (parentElement && isThirdIdx(i) || isLastIdx(i)) {
이런 작은 함수들 좋죠. 

아래 라인을 묶어서 하나의 함수로 만들어도 좋고요.
parentElement && isThirdIdx(i) || isLastIdx(i)

2018-10-30 12:22 UTC, merged