[woogie]추가슬라이딩UI까지 STEP5,6,7
code-squad/javascript-food pull request #59
Opened 2018-11-11 16:03 UTC by Imdonguk

* 메인슬라이드에 있는 클래스를 재사용해 서브슬라이드에 구현
* 애니메이션효과는 CSS transition을 사용
* 베스트추천부분과 테마별로 반찬소개하는 부분 같은 template사용
* 마우스올렸을 시에 새벽배송,전국배송 UI 추가구현

###MenuSlide
* 무한슬라이드 구현
* 컨텐츠 수에 상관없는 슬라이드 구현
* (예외상황) 컨텐츠 수가 4의 배수가 아닐 때도 가능하게 함( content가 9개일 땐 4 - 4 - 1 이렇게 동작)

2018-11-12 02:22 UTC, crongro requested changes
menuSlide가 잘 만들어졌네요. 👍 
재사용 되도록 구현된  코드로 보여서 좋아요.

리뷰남긴 부분중 일부분을 수정하고 넘어가도록 해보죠.

2018-11-12 02:22 UTC, crongro commented on index.html
> +                <div class="user_guide">
css 네이밍 룰을 보면,  _보다는 - (hyphen)을 좀더 많이 사용해요.

2018-11-12 02:22 UTC, crongro commented on js/index.js
> +    url : contentURL.mainDish,
url보다는 구체적인 이름이 있으면 더 좋을 듯.

2018-11-12 02:22 UTC, crongro commented on js/index.js
>  const elements = {
이건 자주 쓰니까, _e 와 같은 축약된 표현도 좋을 듯.

2018-11-12 02:22 UTC, crongro commented on js/index.js
>      elements.body.addEventListener('click', (e) => {
destructuring 잘 활용하기.

2018-11-12 02:22 UTC, crongro commented on js/view/MenuSlide.js
> +    constructor({url, slideListEl, naviEl, viewContentCount = 4, timer = 500}){
초기값 준 건 잘했네요.

2018-11-12 02:22 UTC, crongro commented on js/view/MenuSlide.js
> +    clickPreBtn({lastContentPositionX, maxPositionX}){
clickNextBtn와  중복함수인데, 합칠 수 있을 거 같은데요. 
다른 부분이 별로 없어요. 

this.minusPositionX와 this.plusPositionX 가 다르다면 함수를  인자로 받는 것도 방법일거고요.

2018-11-12 02:22 UTC, crongro commented on js/view/MenuSlide.js
> +        },this.timer);
this.timer 와 같이 this로 접근되는 값을 사용하는데요. 
객체안에서는 이게 자연스러울 수 있지만, resetToInitContent가 불릴때 인자로 timer를 받는 건 어때요?
resetToInitContent(10, this.timer) 
이렇게 되면 resetToInitContent 메서드는 좀더 테스트코드 구현이 쉬운 코드가 됩니다.

2018-11-12 02:22 UTC, crongro commented on js/view/MenuSlide.js
> +    setContentData(data){
메서드 크기가 큰게 없어서 좋습니다.

2018-11-12 02:22 UTC, crongro commented on js/view/MenuSlide.js
> +        const firstContentPositionX = -10;
왜 10이라는 매직넘버가 여기 있어야 하는지 잘 모르겠어요..
왜 10인지..알수가없음요.

2018-11-12 02:22 UTC, crongro commented on js/view/MenuSlide.js
> +        return {
key/value가 같으면 간단하게 객체를 이렇게 표현할 수 있어요.
{firstContetPositionX, lastContentPositionX...}

2018-11-12 02:22 UTC, crongro commented on js/view/MenuSlide.js
> +        this.render(lastView);
render 메서드가 3번 불리는데요,
화면 렌더링을 최소한으로 하려고 노력하는게 중요해요.
한번에 렌더링하는 방법은 없을까요?

2018-11-12 02:22 UTC, crongro commented on js/index.js
> +const sideDishSlide = new MenuSlide({
menuSlide에서 다양한 옵션을 받는 건 재사용컴포넌트를 만드는 중요한 방식이에요.
필요하면 더 추가할 수도 있고, 
함수를 옵션으로 넣어줄 수도 있어요.

2018-11-12 11:21 UTC, Imdonguk commented
수정했습니답! 훨씬만족스럽습니다!

2018-11-13 02:12 UTC, crongro approved these changes
수정확인했어요~
다음단계 고고~!

2018-11-13 02:14 UTC, merged