food
code-squad/javascript-food pull request #6
Opened 2017-12-05 06:39 UTC by wfe-luigi

2017-12-05 06:46 UTC, nigayo commented
커밋메시지를 한글로 좀더 자세하게 서술 하듯 써보시는게 어때요?

2017-12-05 06:48 UTC, wfe-luigi commented
네

2017-12-05 06:52 UTC, crongro requested changes
전체 html구조도 그렇고 css도 그렇고
불필요한 태그가 별로 없이 간결해서 좋아요.

아래 질문에 답변도 좀 해보시고요. 
조금 수정해보죠.

2017-12-05 06:52 UTC, nigayo commented on index.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0">
meta속성은 문서에 대한 정보를 담는 것인데요. viewport는 그중에서 화면의 크기관련해서 어떻게 보여줄 것인가를 결정합니다.
이부분을 한번 공부해두시면 좋아요.
이 속성은 모바일웹에서 특히 이해가 필요합니다.

2017-12-05 06:52 UTC, nigayo commented on main.css
> +    letter-spacing: -0.2px;
모든 px을 em으로 한번 바꿔적용해보세요.
em의 단위에 대한 이해도 먼저 해보시고요.
1em은 몇 px이냐? 이런거부터 확인해보세요.

2017-12-05 06:52 UTC, nigayo commented on main.css
> +    margin : 30px 0 0 46px;
46px과 같이 정교하게 px을 맞출필요가 생기나요?

2017-12-05 06:52 UTC, nigayo commented on main.css
> +    box-sizing: border-box;
이 속성에 대한 값들에 따라 layout이 어떻게 달라지는지 잘 이해하셔야해요.

2017-12-05 06:52 UTC, nigayo commented on main.css
> +    position: relative;
relative은 왜 준거죠?

2017-12-06 02:15 UTC, wfe-luigi commented on main.css
> +    box-sizing: border-box;
네
패딩과 테두리가 내부영역을 늘리지 않도록 합니다.

2017-12-06 02:33 UTC, wfe-luigi commented on index.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0">
넵

2017-12-06 15:29 UTC, wfe-luigi commented on main.css
> +    letter-spacing: -0.2px;
넵
em은 현재 지정된 폰트 크기에 대해서 %로 계산
현재 폰트 크기 12px =>   1em = 12px 
rem은 최상위 요소의 폰트크기를 기준

2017-12-06 15:29 UTC, wfe-luigi commented on main.css
> +    margin : 30px 0 0 46px;
input 태그가 float:left로 설정되어서 위아래 가운데 정렬을 하려고 마진을 주었습니다.

2017-12-06 15:43 UTC, wfe-luigi commented on main.css
> +    position: relative;
자식태그의 position:absolute 적용을 위해서 사용했습니다

2017-12-07 00:38 UTC, nigayo commented on main.css
> +    position: relative;
넵.

2017-12-07 00:40 UTC, crongro approved these changes
마크업은 이정도로 하고 개발진행해보죠.

2017-12-07 00:40 UTC, merged