[Whale] Step5,6,7 구현
code-squad/javascript-food pull request #60
Opened 2018-11-13 09:25 UTC by LOG91

- Step5 슬라이딩 효과
- Step6 무한롤링 슬라이드 구현
- Step7 슬라이드 모듈을 범용적인 모듈로 변경하여 메인반찬,코스요리 추가

2018-11-14 03:41 UTC, crongro requested changes
잘 했네요.
데모도 한번 보러 갈게요.

몇개 설명을 좀 부탁드린 것들 comment해주세요.

2018-11-14 03:41 UTC, crongro commented on js/Util/helper.js
> +export function makeItemScoreByStars(star) {
이건 좀  특별하네요.
어떤 서비스에서도  사용할 수 있는 녀석들만 helper에 모아두면 더 좋을 듯.

2018-11-14 03:41 UTC, nigayo commented on js/View/Slider.js
> +    ajax(this.apiUrl, this.cbRenderByTemplate.bind(this));
bind를 해줘야 하는 이유를 한번 설명해보세요.

2018-11-14 03:41 UTC, nigayo commented on js/engine.js
> +  constructor(header, navModel, bestMenu, promotion, sideMenuSlide, mainMenuSlide, courseMenuSlide) {
생성자의 인자가 많다면 객체로 받는 걸 고려해보세요.

2018-11-14 03:41 UTC, nigayo commented on js/View/Slider.js
> +    qsa('.slider')[this.slideNumber].style.transform = 'translateX(-980px)'
980이런 값을 하드코딩 하지 않도록 해주세요~

2018-11-14 03:41 UTC, nigayo commented on js/templates/slideMenuTpl.js
> +    const slideWrapHTML = list.reduce((acc, cv, idx) => {
reduce가 좀 복잡한 코드네요.
그 전에 filter와 같은 다른 메서드를 먼저 쓸수는 없을지등을 한번 생각해보세요.

2018-11-14 03:41 UTC, nigayo commented on js/View/Slider.js
> +      this.timeChecker = setTimeout(() => this.cbTranslateWithoutTransition(0, qsa('.slider')[number].children.length - 2, number), 700);
여기서는 비동기임에도 this에 바인딩을 안했는데요.
왜 그런지 설명을 좀 해보세요.

2018-11-14 03:41 UTC, nigayo commented on js/View/Slider.js
> +    this.slideNumber = this.getSlideNumber();
his.getSlideNumber() 함수 호출이 두번 일어나고 있음.

2018-11-14 03:41 UTC, nigayo commented on js/View/Slider.js
> +    this.timeChecker = null;
생성자의 속성이 좀 많아요. 
this로 접근가능한 값이 많으면 전역변수의 단점과 같은 문제가 있어요 .
따라서 지역변수로 옮길 수 있는 건 함수함으로 이동시키세요~

2018-11-14 03:41 UTC, crongro approved these changes

2018-11-14 05:32 UTC, LOG91 commented on js/View/Slider.js
> +    ajax(this.apiUrl, this.cbRenderByTemplate.bind(this));
bind를 해주지 않게되면 콜백함수는 전역을 가리키기 때문입니다!

2018-11-14 06:56 UTC, LOG91 commented on js/View/Slider.js
> +      this.timeChecker = setTimeout(() => this.cbTranslateWithoutTransition(0, qsa('.slider')[number].children.length - 2, number), 700);
call을 사용하여 this를 바인딩해도 같은 결과는 나오는데요~
여기서는 하지 않아도 똑같은 this가 바인딩 되는 이유는 화살표함수를 썼기에 전역이 아니라 바로 상위의 class Slider를 가리키기 때문입니다

2018-11-16 04:35 UTC, crongro approved these changes
확인했어요. 
수고했고 이제 다음단계로 !! 

engine과app의 역할이 모호한것은 수정해야 할 듯.ㅎ

2018-11-16 04:36 UTC, merged