tab_ui from json
code-squad/javascript-food pull request #8
Opened 2017-12-11 07:00 UTC by wfe-luigi

2017-12-12 02:46 UTC, crongro requested changes
기본기를 좀 잊지말기요~!

2017-12-12 02:46 UTC, nigayo commented on tab_ui.html
> +<script>
script 파일로 분리해서 개발하세요.!
적어도 PR날릴때는 그렇게하시죠.

2017-12-12 02:46 UTC, nigayo commented on tab_ui.html
> +<style>
css코드는 html상단에 위치하는게 좋겠죠?

2017-12-12 02:46 UTC, nigayo commented on tab_ui.html
> +            var ul = Array.from(document.querySelector(".best_container").children);
array from메서드 브라우저 지원범위도 파악해보시고요.
from메서드의 polyfill을 찾아서 polyfill.js에 추가해보세요.

2017-12-12 02:46 UTC, nigayo commented on tab_ui.html
> +    var i,length = ul.length;
length란.... 네이밍 다시 신경쓰기요~

2017-12-12 02:46 UTC, nigayo commented on tab_ui.html
> +    for(i=1;i<length;i++){
반복문은 for말고 foreach,map,filter로만 써보세요.이제.

2017-12-12 02:46 UTC, nigayo commented on tab_ui.html
> +            var keys = ["detail_hash","image","title","description","n_price","s_price"];
li, keys 이름 다시 짓기.

2017-12-12 02:46 UTC, nigayo commented on tab_ui.html
> +            // keys.forEach(function(key){
PR을 배포하는 느낌으로 생각해주세요.
안쓰는 주석도 말끔하게 제거해봅니다.

2017-12-12 02:46 UTC, nigayo commented on tab_ui.html
> +function bestTabinit(){
동사+명사로~

2017-12-12 02:46 UTC, nigayo commented on tab_ui.html
> +    document.querySelector(".best_tabs").addEventListener("click",function(e){
이벤트리스너가 조금이라도 길어지면, addEventListener메서드에서  분리해서 선언하도록 하세요.

2017-12-12 02:46 UTC, nigayo commented on tab_ui.html
> +        if(e.target && e.target.nodeName == "LI"){
반대사항으로 체크하고 코드를 구현해볼래요?

if(!e.target || !(e.target.nodeName !== "LI")){
}

2017-12-12 05:15 UTC, wfe-luigi commented on tab_ui.html
> +<script>
넵 ;ㅂ;..

2017-12-12 05:15 UTC, wfe-luigi commented on tab_ui.html
> +            // keys.forEach(function(key){
넵

2017-12-12 05:16 UTC, wfe-luigi commented on tab_ui.html
> +function bestTabinit(){
넵

2017-12-12 05:18 UTC, wfe-luigi commented on tab_ui.html
> +<style>
넵

2017-12-12 08:31 UTC, wfe-luigi commented on tab_ui.html
> +            var keys = ["detail_hash","image","title","description","n_price","s_price"];
넵

2017-12-12 10:19 UTC, wfe-luigi commented on tab_ui.html
> +    var i,length = ul.length;
넵

2017-12-12 10:19 UTC, wfe-luigi commented on tab_ui.html
> +    for(i=1;i<length;i++){
넵

2017-12-12 10:22 UTC, wfe-luigi commented on tab_ui.html
> +    document.querySelector(".best_tabs").addEventListener("click",function(e){
넵

2017-12-15 02:04 UTC, crongro requested changes
참고해서 계속 진행해요

2017-12-15 02:04 UTC, nigayo commented on tab_ui/tab_ui.js
> +var data;
함수간의 인자로 넘겨주면 전역변수를 없앨 수 있을거 같은데요.

2017-12-15 02:04 UTC, nigayo commented on tab_ui/tab_ui.js
> +    data = JSON.parse(this.responseText);
data이름도 구체적으로 쓰면 더 좋을 듯.

2017-12-15 02:04 UTC, nigayo commented on tab_ui/tab_ui.js
> +    makeLiList();
이코드가 callback 함수보다 먼저 실행되는거 맞죠? 
알고 계시리라~

2017-12-15 02:04 UTC, nigayo commented on tab_ui/tab_ui.js
> +        var bestDetailUl = document.createElement("Ul");
여기 콜백함수는 너무 긴데요.
리팩토링을 하면 좋겠어요.

반복로직인 너무 중첩되어 있어요.
차라리 절차적으로 결과를 받고 그걸 다시 받아서 돌고 하면 어때요?

forEach()
forEach()
..

2017-12-15 02:04 UTC, nigayo commented on tab_ui/tab_ui.js
> +            var findKeys = ["detail_hash","image","title","description","n_price","s_price"];
makeTab 탭의 변수로 지정하기.

2017-12-20 06:02 UTC, wfe-luigi commented on tab_ui/tab_ui.js
> +    makeLiList();
넵

2017-12-21 04:46 UTC, crongro requested changes
리뷰보냅니다.
tab도 객체화 하시고요.
HTML에서  JS코드를 분리해서 항상 개발하세요.

2017-12-21 04:46 UTC, crongro commented on slide_ui/index.html
> +        oReq.addEventListener("load", function() {
ajax코드가 또 불릴 수 있을 거 같아요.
다른 UI에서도 쓸 수 있게 ajax함수를 범용함수로 수정해보죠.
예를들어 여기 라인의 function(콜백)을 ajax의 인자로 받는 등으로 처리가능하겠네요.

2017-12-21 04:46 UTC, crongro commented on slide_ui/index.html
> +        index : 0,
index부터 pagination과 같은 값은 이렇게 초기화하는게 어때요? 
```javascript
var slide = {
  initSlide : function() {
    this.index = 0;
    this.slides = doc.query("...");
    this.slideList = null;
  }
```

2017-12-21 04:46 UTC, crongro commented on slide_ui/index.html
> +                    this.slideList.children[index].className = "show";
show함수에서 선언하는 것보다,  대상을(this.slideList.chidren)을 인자로 받아서 처리하면
더 범용적인 함수로 발전할 수 있을 듯.

2017-12-21 04:46 UTC, crongro commented on slide_ui/index.html
> +                    this.index+1 == this.length ? this.index = 0 : this.index++;
이게 되나요? 
값을 할당하는 과정에서 this.index+1은 좀 보기 거북해보여요..

2017-12-21 04:46 UTC, crongro commented on slide_ui/index.html
> +            document.querySelector(".slide_pagination > ul").addEventListener("click",function(e){
arrow function 사용법을 익히고 이제 사용해봐요.
주로 콜백함수에서 사용하면 될 겁니다.

2017-12-21 04:46 UTC, crongro commented on slide_ui/index.html
> +                    document.querySelector(".slide_pagination > ul").children[index].className = "on";
이렇게 반복적인 dom 엘리먼트노드는 캐시해두고 쓰면 좋죠.

var el = document.querySelector(".container_slide > ul").children[index];
el.className = "hide";

2017-12-21 05:13 UTC, wfe-luigi commented on slide_ui/index.html
> +                    this.index+1 == this.length ? this.index = 0 : this.index++;
넵
last = length-1;

2017-12-21 05:14 UTC, wfe-luigi commented on slide_ui/index.html
> +            document.querySelector(".slide_pagination > ul").addEventListener("click",function(e){
넵

2017-12-21 05:20 UTC, wfe-luigi commented on slide_ui/index.html
> +                    document.querySelector(".slide_pagination > ul").children[index].className = "on";
넵

2017-12-29 02:17 UTC, crongro requested changes
약간 수정해보죠.

2017-12-29 02:17 UTC, nigayo commented on slide_ui/index.html
> +            document.querySelector(".slide_pagination > ul").addEventListener("click",function(e){
init 함수는 무엇을 하는지에 대한 요약정보를 볼 수 있으면 더 좋겠어요.
예를들어 이벤트를 등록하는 이 부분을 별도 함수로 분리할 수 있겠네요.

2017-12-29 02:17 UTC, nigayo commented on slide_ui/index.html
> +                    var index = Array.prototype.indexOf.call(p.children, e.target.parentElement);
call동작에 대해서 설명할 수있어야 해요. 알쥬?

2017-12-29 02:17 UTC, nigayo commented on slide_ui/index.html
> +                    var index = Array.prototype.indexOf.call(p.children, e.target.parentElement);
e.target을 반복적으로 쓰는데, var target = e.target으로 변수로 캐시해서 사용하는게 더 빠른코드.

2017-12-29 02:17 UTC, nigayo commented on slide_ui/index.html
> +        var oReq = new XMLHttpRequest();
이제 모든 변수 선언을 const와 let으로 바꿔보세요.
var는 이제 그만 사용.

2017-12-29 02:27 UTC, wfe-luigi commented on slide_ui/index.html
> +        var oReq = new XMLHttpRequest();
넵

2017-12-29 02:30 UTC, wfe-luigi commented on slide_ui/index.html
> +            document.querySelector(".slide_pagination > ul").addEventListener("click",function(e){
넵

2017-12-29 02:30 UTC, wfe-luigi commented on slide_ui/index.html
> +                    var index = Array.prototype.indexOf.call(p.children, e.target.parentElement);
넵

2017-12-29 02:38 UTC, crongro requested changes
잘 하셨어요. 
몇개만 더 수정해보죠.

2017-12-29 02:38 UTC, nigayo commented on slide_ui2/slide_ui.js
> +    template :  `
Slide생성자에서 인자로 받아서 이 컴포넌트에서는 이부분을 제외시키기.

2017-12-29 02:38 UTC, nigayo commented on slide_ui2/slide_ui.js
> +        oReq.addEventListener("load",function(){
이 부분을 컴포넌트에서 빼서, 별도 유틸리티에서 추가해보죠?

2017-12-29 02:38 UTC, nigayo commented on slide_ui2/slide_ui.js
> +        this.slideList.children[index].className = "show";
css classname도 생성자에서 인자로 받아보세요.

2017-12-29 02:38 UTC, nigayo commented on slide_ui2/util.js
> +function $on(target, type, callback, capture) {
왜 이녀석만 $가 붙었죠? 
qs, qsa 는 아니고? 
사용하는 입장에서는 일관된 api를 만드는게 중요해요.

2017-12-29 02:42 UTC, wfe-luigi commented on slide_ui2/slide_ui.js
> +    template :  `
넵

2017-12-29 02:42 UTC, wfe-luigi commented on slide_ui2/slide_ui.js
> +        oReq.addEventListener("load",function(){
앗 넵

2017-12-29 02:45 UTC, wfe-luigi commented on slide_ui2/util.js
> +function $on(target, type, callback, capture) {
넵

2018-01-09 09:29 UTC, merged