Sphilee
code-squad/javascript-food pull request #9
Opened 2017-12-19 08:33 UTC by sphilee

2017-12-20 01:20 UTC, crongro approved these changes
코멘트참고하시고요.
function - prototype형태로 바꿔보세요.

2017-12-20 01:20 UTC, nigayo commented on helpers.js
> +    window.qs = function (selector, scope) {
window(전역공간)에 계속 함수를 추가하는 건 전역공간을 오염시켜서 좋은건 아닌거 같아요.
모든 public메서드에 prefix로 이름을 정해주는 것도 방법일 듯.
$on처럼요

2017-12-20 01:20 UTC, nigayo commented on helpers.js
> +     * @param {Element} element
jsdoc문법인가요?
나중에 문서로 한번 만들어보세요.

2017-12-20 01:20 UTC, nigayo commented on slide.js
> +        initBanchan();
만약 setView함수 안에서, initBanchan메서드 뒤에 다른 코드를 넣으면, 
initBanchan 메서의 실행결과 이후에 실행될까요? 아니면 그 전에 실행될까요?

2017-12-20 01:20 UTC, nigayo commented on slide.js
> +    async function initBanchan() {
async를 사용해서 얻은 장점은 어떤거에요? 
만약 없었다면 어땠을거 같아요?

2017-12-20 01:20 UTC, nigayo commented on slide.js
> +    async function initBanchan() {
initBanchan 메서드부터 분리해야겠네요.
메서드를 분리하고, 함수들간에 '인자'를 통해서 값을 많이 전달하고요.
특히 로직과 관련 없는 template작업(view)부분을 분리해보는 게 좋겠네요.

2017-12-20 01:20 UTC, nigayo commented on slide.js
> +            const foodBoxStrs = value.items.map(item => foodBoxTemplate.innerHTML
foodBoxTemplate과 위의 es6 template literal은 다른방식으로 처리되는거네요.
두 가지 사용법에 대해서 잘 이해하고 계세요.

다음과제때는 한가지 방법으로 통일해서 진행해보도록 해보죠.

2017-12-20 01:20 UTC, nigayo commented on slide.js
> +                const deliveryType = `<div class='food_img_hover'><ul>${item.delivery_type ? item.delivery_type.map(type => `<li><span>${type}</span></li>`).join('') : ''}</ul></div>`;
여기 문법은 템플릿처리라 어쩔수 없다고 치고, 개행이라도 해서 보기 좋게해보죠.

2017-12-20 07:11 UTC, sphilee commented on slide.js
> +        initBanchan();
initBanchan 실행결과 이후에 실행됩니다.
그러나 initBanchan 메서드안에 비동기 함수가 있을경우 비동기 함수 실행 이전에 뒤에 코드가 먼저 실행됩니다.

2017-12-20 07:20 UTC, sphilee commented
@nigayo 수정했습니답!

2017-12-20 07:20 UTC, sphilee commented on slide.js
> +    async function initBanchan() {
ajax 호출 이전에 다음코드가 실행됩니다.

2017-12-20 07:21 UTC, sphilee commented on slide.js
> +            const foodBoxStrs = value.items.map(item => foodBoxTemplate.innerHTML
handlebar를 활용해보았습니다.

2017-12-21 04:55 UTC, crongro requested changes
지금 수정하고 있는듯 한데, 
initBanchan은좀더 분리하시고요.

2017-12-21 04:55 UTC, nigayo commented on src/main.js
>          }, 1000);
1초뒤에 실행되는것이 왜죠?

2017-12-21 04:55 UTC, nigayo commented on slide.js
> +    async function initBanchan() {
initBanchan은 아직 분리안한거죠? 더 분리해보세요.

2017-12-21 05:02 UTC, sphilee commented on src/main.js
>          }, 1000);
수정했습니답 실수입니답.

2017-12-21 05:22 UTC, crongro approved these changes
코드가 많이 좋아졌네요.
그런데 MVC상태에서 다른기능( 컴포넌트)가 추가되면 어떻게 될지 고민스러울 거 같아요. 이부분을 고민해서 풀어보세요.
특히 기능이 많아지면 controller가 커질 수도 있어보여요.
view가 더 많아지면 view도 여러개 나눌수 있을거에요.
이부분은 참고하세요.

전체적인 메서드 단위는 좋습니다.

알아서 import/export를 잘 썼네요.

아래내용 정리하고 저에게 정리된 블로그를 슬랙에 공유해주세요.
- template사용에 대한 몇가지 적용방식 ( 최종적용한  handlerbar+webpack+import 방식포함)

2017-12-21 05:22 UTC, crongro commented on src/controller.js
> +    async initSlide() {
너무 인자를 안써요. url같은 값은 인자로 받아서 사용하세요.

2017-12-21 05:22 UTC, nigayo commented on src/controller.js
> +    moveSlides(n) {
moveSlides와 같은 내용을 controller에 만들어둔게 좋은 거 같네요.
여러 뷰를 컨트롤 해주는 작업을 controller의 메서드를 통해서 진행할 수 있으니 view간에 호출은 없어진 듯.

2017-12-21 05:22 UTC, nigayo commented on src/view.js
> +import foodBoxTemplate from '../template/foodBox-tpl.html';
알아서 잘 썼네요? 
template을 이렇게 불러와서 사용하는 방법도 괜찮아보임.

2017-12-21 05:22 UTC, nigayo commented on src/view.js
> +                foodBox[i * 3 + j].insertAdjacentHTML('beforeend', badgeTemplate({
3 이런건 변경될 수 있는 것이니..수정해보세요.

2017-12-21 07:35 UTC, crongro approved these changes
다음단계 진행해보죠.
mvc형태를 유지하면서 가면 좋을 거 같아요.
그러면서 생기는 문제를 해결해보도록 하죠.

2017-12-28 08:08 UTC, sphilee commented
@nigayo 무한 슬라이딩까지 했습니답!

2017-12-29 02:26 UTC, crongro requested changes
몇 개 코멘트 남겼고요.
무엇보다 view를 좀 분리하는 게 좋아보이네요.

2017-12-29 02:26 UTC, nigayo commented on src/controller.js
> +        this.slideImgs = await request(url);
request에서 reject처리가 되는 경우를 고려해서 에러처리를 해볼래요? try/catch로.
catch에 에러가 잘 들어오는지까지보고, console.error등으로 출력하는 정도.(개발자에게 에러를 노출하는걸 목표로)

2017-12-29 02:26 UTC, nigayo commented on src/controller.js
> +        if (this.direction === -40) this.direction = -20;
이런 데이터(40,20..)는 컴포넌트가 초기화될때 옵션값으로 받도록 해보세요.
옵션(함수의 인자)이 많아지면 컴포넌트의 재사용성이 올라가겠죠?

2017-12-29 02:26 UTC, nigayo commented on src/helpers.js
> +export function throttle(func, wait) {
아쉽네요. throttle 코드는 직접 구현해보는게 좋습니다.
지금 문제를 해결하기 위한용도로만, 다시 구현해보는건 어때요?

2017-12-29 02:26 UTC, nigayo commented on src/view.js
> +        this.foodTabEl.insertAdjacentHTML('afterbegin', food.map(value => foodTabTemplate({
조금더 보기 좋게 하려면, 
food.map(value => foodTabTemplat 
이 부분을 분리해서 결과를 변수에 담아두는 게 좋을 듯.

2018-01-02 02:14 UTC, sphilee commented
@nigayo 리뷰반영 했습니답!

2018-01-02 05:29 UTC, crongro approved these changes
조금만 더 수정하시고 다음단계로 넘어가보죠.
일단 승인!

2018-01-02 05:29 UTC, nigayo commented on src/view.js
> +    bindSlidesPrev(handler) {
bind 로 시작하는 메서드가 한줄만 모두 있으니, 그냥 메서드를 묶어두어도 좋겠다는 생각입니다.
본인도 고민해보세요.

2018-01-02 05:29 UTC, nigayo commented on src/view.js
> +        this.sideFoodBoxEl.style.transitionDuration = '0.5s';
이것이랑 renderResetSideSlides 메서드는 내용이 중복인거 같은데요? 
더구나 유틸리티처럼 분리해도 되는 거 같아보이기도 하고요.

2018-01-02 05:29 UTC, nigayo commented on src/helpers.js
> +export function throttle(func, limit) {
오~ 이해한코드죠? 
개념을 잘 이해해두고, 이 코드를 다른 플젝에서도 잘 쓰일 수 있게 해보죠.

2018-01-02 05:29 UTC, nigayo commented on src/controller.js
> +        this.initSlide('http://home.dotol.xyz/php/test_api.php');
this.slideindex, this.direction그리고 여기 uRL들이 
src/app.js쪽에서 인자로 넣어서 controller를 실행하면 어때요? 
지금은 data들이 모두 controller안에 있어서.. 하드코딩 한 듯한 느낌입니다.

2018-01-02 05:29 UTC, nigayo commented on src/controller.js
> +            console.error(e);
에러메시지를 좀더 자세하는 게 실전에서는 필요할 듯 해요.

2018-01-03 01:14 UTC, crongro approved these changes
잘했어요.
일단 이상태처럼 view를 나눈 상태로 앞으로도 개발하면 좋겠는데요.

2018-01-03 01:14 UTC, merged